### ISSUE TITLE
Please Provide Validation against the possible Attachment MimeTypes

### ISSUE THREAD

**Issue by thomaspz** [itplr-kosit/validator-configuration-xrechnung#20]
If I use an unsupported MimeType in Additional-Documents, no Validation Errors are thrown.

From 1.2.0 spec : https://www.xoev.de/sixcms/media.php/13/XRechnung-v1-2-0.pdf

```
Der MIME Code des angehängten Dokumentes. Zugelassen sind die Codes
• application/pdf
• image/png
• image/jpeg
• text/csv
• application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
• application/vnd.oasis.opendocument.spreadsheet
```

[01.15a-INVOICE_ubl_nicht_unterstuezter_mimetyp.xml.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/4413629/01.15a-INVOICE_ubl_nicht_unterstuezter_mimetyp.xml.zip)

If I vaildate the example Invoice 01_15_ubl with embeed Document, but not supported Mime-Type, the validation is o.k.; Expected : Validation error.

Please add validation Rules for supported Mime-Types from additional Documents defined in spec.

**Comment by rkottmann** [comment]
thx for reporting, this is scheduled for this year summer release.  See also https://projekte.kosit.org/xrechnung/xrechnung/issues/59

**Comment by rkottmann** [comment]
should have been fixed by the summer release. Hence closing.

**Comment by tze** [comment]
I think this is still an issue for CEFACT. Please have a look at #40
