### ISSUE TITLE
false positive validation warning [BR-DEX-02] when using SubInvoiceLine and AllowanceCharge

### ISSUE THREAD

**Issue by landrix** [itplr-kosit/validator-configuration-xrechnung#41]
i think it's a false positive when using SubInvoiceLine and AllowanceCharge on InvoiceLine-level

[BR-DEX-02] Der Wert von "Invoice line net amount" (BT-131) einer "INVOICE LINE" (BG-25) oder einer "SUB INVOICE LINE" (BG-DEX-01) soll der Summe der "Invoice line net amount" (BT-131) der direkt darunterliegenden "SUB INVOICE LINE" (BG-DEX-01) entsprechen.

see attached document

[XRechnung-UBL-200.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/5533272/XRechnung-UBL-200.zip)

**Comment by rkottmann** [comment]
see also #48

**Comment by rkottmann** [comment]
we working on this right now

**Comment by rkottmann** [comment]
it is fixed see #48

**Comment by landrix** [comment]
in which release it will be fixed?

not in:

https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/tag/release-2020-12-31

the warning still exists

**Comment by rkottmann** [comment]
hmm, should not be, @lkumai may you have a look at this?
